const usersTableHeaderText = 'Users'
const usersSideNavigationId = 'VerticalNavigationMenuItem::tab_navigation1--0_0'
const retoolGridUsersId = 'RetoolGrid::Main'
const userNameColumnId = 'HeaderCellContents::Label::3bc01'
const userFullNameColumnId = 'HeaderCellContents::Label::f048b'
const retoolGridProfileLabel = 'Profile'
const retoolGridClipsLabel = 'Clips'
